name: "First github action"
description: "Say hello after each pull request"
author: "Rafael"

inputs:
  GITHUB_TOKEN:
    description: "Github token"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"